repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^_reference/
      - id: end-of-file-fixer
        exclude: ^_reference/
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file]
        files: \.(cpp|h|hpp)$
        exclude: ^_reference/

  - repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.2
    hooks:
      - id: cmakelint
        args: ['--filter=-linelength']
